### ISSUE TITLE
Issue on page /Text-Analysis/TF-IDF-Scikit-Learn.html

### ISSUE THREAD

**Issue by ionFreeman** [melaniewalsh/Intro-Cultural-Analytics#13]
You call `tfidf_df = tfidf_df.stack().reset_index()` a second time (cell 280)

**Comment by melaniewalsh** [comment]
The first time I call `tfidf_df.stack().reset_index()`, the changes are not permanent because I didn't re-assign to the `tf_idf` DataFrame. So that's why I call it again. Let me know if you see something different. Thanks for reading!
