### ISSUE TITLE
Issue on page /04-Data-Collection/12-Twitter-Data.html

### ISSUE THREAD

**Issue by igorbrigadir** [melaniewalsh/Intro-Cultural-Analytics#14]
Thanks for writing this up! I linked it in the twarc docs too.

To explain the tweets that were there but did not match the query: 

This is because `twarc-csv` when converting the raw data to CSV, will put `referenced_tweets` inline with the result tweets.

So, if a reply to a tweet matches a query, the tweet being replied to is included in `referenced_tweets` - by default `twarc-csv` pulls these out and includes them to give you all of the data available. To prevent this and restrict it to only the matching tweets, you can specify `--no-inline-referenced-tweets` like:

```
twarc2 csv --no-inline-referenced-tweets input.jsonl output.jsonl
```

other parameters that may be helpful are included in https://github.com/DocNow/twarc-csv (i haven't added those to the 
main docs unfortunately)

The other small thing i noticed is using `>` the output redirect to specify output files. While this is correct and expected usage, and will work - we've noticed people running into trouble on Windows machines if they do it this way. The encoding of the output files gets messed up, so instead, i would recommend using the explicit file output argument (simply omitting the `>`)

```
twarc2 search --archive "query" output.jsonl
```

Another issue that crops up is using and escaping `"` quotes when using phrases. This is annoying in Windows too - in Mac and Linux this is straight forward, escaping `"` inside the query with `\` like:

```
twarc2 search "-is:retweet \"David Foster Wallace\" (fanboy OR bro)" dfw.jsonl
```

but on Windows it's a bit messy, because it's different for different shells, one way that seems to work is using tripple quotes `"""`:

```
twarc2 search """-is:retweet "David Foster Wallace" (fanboy OR bro)""" dfw.jsonl
```

Let me know if you want this in the form of a PR instead.

**Comment by melaniewalsh** [comment]
This is fantastic! Thanks so much, @igorbrigadir. The fact that `twarc-csv` includes referenced tweets clears up a lot of questions, and I will be sure to explain everything in my tutorial. I will also update the syntax for outputting files and using/escaping quotation marks. It's incredibly helpful to know that this is a pain for Windows users (usually I have to wait for my students with Windows computers to run into trouble). I hope to update my tutorial by the end of the day!

**Comment by melaniewalsh** [comment]
@igorbrigadir I tried to clarify what's going on with the referenced tweets and included the updated syntax: https://melaniewalsh.github.io/Intro-Cultural-Analytics/04-Data-Collection/12-Twitter-Data.html Let me know if you have other thoughts or suggestions!
