### ISSUE TITLE
Issue on page /05-Text-Analysis/Multilingual/Portuguese/02-Named-Entity-Recognition-Portuguese.html

### ISSUE THREAD

**Issue by ericbrasiln** [melaniewalsh/Intro-Cultural-Analytics#16]
Hello, Melanie.
I've notice that the output example for Portuguese NER is a text in Spanish.

Your book is amazing! Congratulations. It's a main reference for me and im using it as inspiration for my class on digital history.

**Comment by melaniewalsh** [comment]
Good catch, @ericbrasiln! It should be fixed now, but let me know if you notice any other mistakes.

Also thank you for the kind words! I'm glad the book has been useful :D
