### ISSUE TITLE
categories_by_topics.pdf iframe not rendering in jupyterbook

### ISSUE THREAD

**Issue by jnothman** [melaniewalsh/Intro-Cultural-Analytics#18]
**Describe the bug**

`topic-model-output/NYT-obits/categories_by_topics.pdf` is included in an iframe in https://github.com/melaniewalsh/Intro-Cultural-Analytics/blob/master/book/05-Text-Analysis/08-Topic-Modeling-Text-Files.ipynb. It does not render appropriately for me in the jupyterbook edition.

**To Reproduce**
1. Go to [08-Topic-Modeling-Text-Files](https://melaniewalsh.github.io/Intro-Cultural-Analytics/05-Text-Analysis/08-Topic-Modeling-Text-Files.html)
2. Find in page " PDF "
3. See "Whoops Page Not Found"

**Expected behavior**

No Whoops

**Screenshots**

![image](https://user-images.githubusercontent.com/78827/146725186-c1f067ac-a473-4f81-a832-a906f7ed442b.png)

**Comment by melaniewalsh** [comment]
Thanks for catching this, @jnothman! It should be fixed now 👍
