### ISSUE TITLE
Invalid characters for a filename

### ISSUE THREAD

**Issue by akhadianharnowo** [melaniewalsh/Intro-Cultural-Analytics#3]
Thanks for sharing the book. I think this is an excellent set of Python lessons that is neatly structured and delivered. I was surprised by the content you included in the book; I thought it was too much for a semester, especially for an intro class. But after reviewing your clear and concise explanation in each module, I believe it is doable. Furthermore, the transition between topics is smooth, and I enjoyed it. Well done!

Would you mind if I adapt some of your lessons and structures? Also, I found an invalid symbol in one of your CSV files that stopped me from cloning your book.  You can find the said file here: book/texts/literature/Lost-in-the-City-HTRC-Extracted-Features/Lost-in-the-City-HTRC-Extracted-Features(>5PerStory).csv  I will try again once you rename the file.

Thanks.
-Dion

**Comment by melaniewalsh** [comment]
Thank you for the kinds words, Dion! And thanks for bringing up the invalid character. I will fix it soon.

Also I don't mind if you adapt my materials at all! I'm planning to add a suggested citation to the website:
Melanie Walsh, _Introduction to Cultural Analytics & Python_, Version 1, 2021

**Comment by akhadianharnowo** [comment]
Thanks, Melanie. I will definitely use that citation when using your works!

**Comment by melaniewalsh** [comment]
Should be fixed now! Out of curiosity, are you a Windows user?

**Comment by akhadianharnowo** [comment]
Thanks, it worked! Yes, Windows foreva :D
