### ISSUE TITLE
Issue on page /Data-Collection/Twitter-API-Setup.html

### ISSUE THREAD

**Issue by emonson** [melaniewalsh/Intro-Cultural-Analytics#6]
There is a line that cuts off before it's supposed to end in number 5 under "Apply for a Twitter Developer Account". Right under the image in section 5.

**In English, please describe how you plan to use Twitter data and/or APIs. For students and teachers, please include the name of the school, the name of the instructor and the course number (i

**Comment by melaniewalsh** [comment]
Thanks, Eric!
