### ISSUE TITLE
Issue on page /Data-Collection/Twitter-Data-Collection.html

### ISSUE THREAD

**Issue by emonson** [melaniewalsh/Intro-Cultural-Analytics#7]
There are a couple spots on this page where you use language like, "To collect tweets from approximately 7 days in the past", or "in real time or ~7 days in the past". I was confused by this, thinking it meant that you could either get tweets from today, or from specifically 7 days in the past. From what you say elsewhere I can see that what you mean is that you can get them from a time window that extends from the present to about 7 days in the past. It's much more clear to me in the places where you say something like "from the past 7 days". That doesn't confuse me.

**Comment by melaniewalsh** [comment]
That's a great point. You're right that it's confusing. I've changed the wording based on your suggestions. Cheers!
