### ISSUE TITLE
Potential error in Data-Analysis/Pandas-Basics-Part1-In-Class.ipynb

### ISSUE THREAD

**Issue by lachlansimpson** [melaniewalsh/Intro-Cultural-Analytics#8]
Potential mistake on [line of code](https://github.com/melaniewalsh/Intro-Cultural-Analytics/blob/94f80b85a85db3e08b207e43dbe93f9583a7c22b/book/Data-Analysis/Pandas-Basics-Part1-In-Class.ipynb#L128) under "Read in CSV File" header. I presume this is either a mistake or a deliberate move for a "teaching moment". Please excuse if it's the second.

This fails with a `File Not Found` error.

```
pd.read_csv('Bellevue_Almshouse_Dataset.csv', delimiter=',', encoding='utf-8')
```
Given the current file structure, it should read:

```
pd.read_csv('In-Class/Bellevue_Almshouse_Dataset.csv', delimiter=',', encoding='utf-8')
```

**Comment by lachlansimpson** [comment]
As I quickly discovered - both lines of code in this section are affected by this.

**Comment by melaniewalsh** [comment]
Hi Lachlan, yes, this file was in the wrong directory. This is an experimental section, which is why it's not linked in the TOC on the website, but I've fixed it for now. Cheers
