### ISSUE TITLE
Issue on page /Network-Analysis/Making-Network-Viz-with-Bokeh.html

### ISSUE THREAD

**Issue by madegomez** [melaniewalsh/Intro-Cultural-Analytics#9]
Hello

I wanted to know how to add a legend referring to the colors of the nodes or colors of the arcs?

**Comment by melaniewalsh** [comment]
Oh that's interesting! I haven't incorporated legends into the networks yet, but there's information about how you might do so in Bokeh's documentation: https://docs.bokeh.org/en/latest/docs/user_guide/interaction/legends.html
